name: Netlify

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out ğŸ›
        uses: actions/checkout@v3

      - name: Set Node ğŸ”§
        uses: actions/setup-node@v3
        with:
          node-version: 17.x

      - name: Cache node_modules ğŸ“¦
        uses: actions/cache@v2
        id: cache-yarn
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: Install dependencies ğŸ§‘â€ğŸ’»
        run: yarn install --frozen-lockfile

      - name: Generate ğŸ­
        run: yarn generate

      - name: Archive Artifact ğŸ“®
        uses: actions/upload-artifact@master
        with:
          name: .output
          path: .output

  deploy:
    name: Deploy
    needs: generate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v3

      - name: Download Artifact ğŸ“¬
        uses: actions/download-artifact@master
        with:
          name: .output
          path: .output

      - name: Deploy to Netlify ğŸš€
        run: npx netlify-cli deploy --dir=.output --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
